name: send_remider_to_user
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # my_plugin:
  # path: /path/to/your/plugin

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^2.0.6

  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.3

  # Flogs, a powerful logging framework
  #  f_logs: ^1.2.2

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^5.0.0

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^3.0.0

  # A powerful Http client for Dart
  dio: ^4.0.0

  # A flexible widget for user notification. Customize your text, button, duration, animations
  # and much more. For Android devs, it is made to replace Snackbars and Toasts.
  another_flushbar: ^1.10.23

  # Material Dialog
  material_dialog: ^1.0.0-nullsafety.1

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.1.0+2
  path_provider: ^2.0.2

  # for dependency injection
  get_it: ^7.1.3
  image_picker: any
  file_picker: any
  flutter_local_notifications: ^14.1.1
  awesome_notifications: ^0.6.18+2

  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.15

  firebase_crashlytics: any
  firebase_analytics: any
  flutter_timezone: ^1.0.6
  device_info_plus: ^9.0.2
  fluttertoast: ^8.2.1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_sliders: ^21.2.3
  flutter_xlider: ^3.5.0
  omni_datetime_picker: ^1.0.7
  dropdown_button2: ^2.1.0
  calendar_view: ^1.0.3
  date_picker_timeline: ^1.2.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  device_info: ^2.0.0
  hive: any
  hive_flutter: any
  connectivity_plus: any
  url_launcher: ^6.0.10
  cloud_functions: ^3.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0
  mobx_codegen: ^2.0.1+3
  # build_runner: ^1.12.2
  build_runner: ^2.3.3
  # analyzer: ^1.4.0
  flutter_lints: ^2.0.0
  hive: any
  hive_flutter: any
  # path_provider: ^2.0.0
  # file_picker: ^4.6.0
  hive_generator: any

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

# For information on the generic Dart art of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
